/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CenterAdminRouteImport } from './routes/center-admin'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as VerifierRouteImport } from './routes/verifier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CenterAdminRoute = CenterAdminRouteImport.update({
  id: '/center-admin',
  path: '/center-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierRoute = VerifierRouteImport.update({
  id: '/verifier',
  path: '/verifier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/center-admin': typeof CenterAdminRoute
  '/command-center': typeof CommandCenterRoute
  '/employee': typeof EmployeeRoute
  '/finance': typeof FinanceRoute
  '/insights': typeof InsightsRoute
  '/super-admin': typeof SuperAdminRoute
  '/verifier': typeof VerifierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/center-admin': typeof CenterAdminRoute
  '/command-center': typeof CommandCenterRoute
  '/employee': typeof EmployeeRoute
  '/finance': typeof FinanceRoute
  '/insights': typeof InsightsRoute
  '/super-admin': typeof SuperAdminRoute
  '/verifier': typeof VerifierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/center-admin': typeof CenterAdminRoute
  '/command-center': typeof CommandCenterRoute
  '/employee': typeof EmployeeRoute
  '/finance': typeof FinanceRoute
  '/insights': typeof InsightsRoute
  '/super-admin': typeof SuperAdminRoute
  '/verifier': typeof VerifierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/center-admin'
    | '/command-center'
    | '/employee'
    | '/finance'
    | '/insights'
    | '/super-admin'
    | '/verifier'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/center-admin'
    | '/command-center'
    | '/employee'
    | '/finance'
    | '/insights'
    | '/super-admin'
    | '/verifier'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/center-admin'
    | '/command-center'
    | '/employee'
    | '/finance'
    | '/insights'
    | '/super-admin'
    | '/verifier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CenterAdminRoute: typeof CenterAdminRoute
  CommandCenterRoute: typeof CommandCenterRoute
  EmployeeRoute: typeof EmployeeRoute
  FinanceRoute: typeof FinanceRoute
  InsightsRoute: typeof InsightsRoute
  SuperAdminRoute: typeof SuperAdminRoute
  VerifierRoute: typeof VerifierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/center-admin': {
      id: '/center-admin'
      path: '/center-admin'
      fullPath: '/center-admin'
      preLoaderRoute: typeof CenterAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier': {
      id: '/verifier'
      path: '/verifier'
      fullPath: '/verifier'
      preLoaderRoute: typeof VerifierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CenterAdminRoute: CenterAdminRoute,
  CommandCenterRoute: CommandCenterRoute,
  EmployeeRoute: EmployeeRoute,
  FinanceRoute: FinanceRoute,
  InsightsRoute: InsightsRoute,
  SuperAdminRoute: SuperAdminRoute,
  VerifierRoute: VerifierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
